world: 'world' //世界名,默认为主世界，一般无需修改
x1: 0     //传送地点X坐标
y1: 0     //传送地点Y坐标
z1: 0     //传送地点Z坐标
r: 1      //粒子效果生成半径
count: 10 //单个粒子效果生成次数（生成密度）
offset: 0   //高度偏移设置
particle: 'END_ROD'   //粒子效果类型
step: 3    //生成步长
isPartOn: true  //是否开启粒子效果
isComOn: true   //是否开启指令执行
Command: 'help' //执行的指令
